[Service]
Environment=POKEMON_STREAM_ENABLED=1
Environment=POKEMON_STREAM_REMOTE_ENABLED=1
Environment=POKEMON_STREAM_USER=SVER-YV
Environment=POKEMON_STREAM_UPLOAD_INTERVAL=2
Environment=POKEMON_REMOTE_STREAM_UPLOAD_INTERVAL=300
Environment=POKEMON_STREAM_SPRITE_ID=0
